### ISSUE TITLE
Answer "Why another date utils library?" in README

### ISSUE THREAD

**Issue by antris** [continuouscalendar/dateutils#2]
There's no clear advantage of this library stated in the README. Especially I am interested in comparison against [moment.js](http://momentjs.com/)

**Comment by eeroan** [comment]
Good point. I will write that. Here's a short answer: dateutils vs moment:
- much smaller and not a feature creep
- favors immutability
- no "method overloading"
- datetime can contain only valid values
- calculations, formatting, parsing, localizations, ranges split into separate small modules
- continuouscalendar uses it
