### ISSUE TITLE
Include dateutils in GH pages

### ISSUE THREAD

**Issue by pihvi** [continuouscalendar/dateutils#4]
Browsing http://continuouscalendar.github.io/dateutils/docs/ should have dateutils included in the page so I can test it in console.

Expected behavior:
1. Open http://continuouscalendar.github.io/dateutils/docs/ in Chrome
2. Open Chrome console
3. type: DateTime.fromDateTime(2010, 12, 15, 14, 35).plusDays(10).toISOString()
4. press enter and expec result: 2010-12-25T14:35:00

**Comment by eeroan** [comment]
Great idea. Do you have a working solution ready or would you like me to do it?

**Comment by pihvi** [comment]
don't have a solutin






On Fri, Jul 29, 2016 at 5:53 PM +0300, "Eero Anttila" <notifications@github.com> wrote:












Great idea. Do you have a working solution ready or would you like me to do it?
